#!/usr/bin/env python3
"""Generate a tiny, innocuous sample tone as a base64 data URI for the static demo.

The hosted demo has no backend and ships no real recordings, but the UI still has
<audio> players. This writes a short synthetic tone to site/demo/assets/audio.js as
`window.__DEMO_AUDIO`, which the demo applies to every player. Re-run to regenerate.

Usage:
    python tools/gen_sample_audio.py
"""
import os
import io
import math
import wave
import struct
import base64

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "site", "demo", "assets", "audio.js"))


def make_wav_bytes(seconds: float = 0.9, rate: int = 8000, freq: float = 220.0,
                   vol: float = 0.16) -> bytes:
    n = int(seconds * rate)
    fade = int(rate * 0.08)
    buf = io.BytesIO()
    w = wave.open(buf, "wb")
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(rate)
    frames = bytearray()
    for i in range(n):
        env = min(1.0, i / fade, (n - i) / fade)  # gentle fade in/out
        s = vol * env * math.sin(2 * math.pi * freq * (i / rate))
        frames += struct.pack("<h", int(s * 32767))
    w.writeframes(frames)
    w.close()
    return buf.getvalue()


def main() -> None:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    b64 = base64.b64encode(make_wav_bytes()).decode("ascii")
    uri = f"data:audio/wav;base64,{b64}"
    with open(OUT, "w") as f:
        f.write("// Auto-generated by tools/gen_sample_audio.py — a tiny synthetic tone.\n")
        f.write("// No real recordings are shipped with the demo.\n")
        f.write(f'window.__DEMO_AUDIO = "{uri}";\n')
    print(f"wrote {OUT} ({len(b64)} base64 chars)")


if __name__ == "__main__":
    main()
